service: crawlers
frameworkVersion: '~3'
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:AWS_REGION}
  stackTags:
    Team: Crawler
custom:
  localstack:
    # debug: true
    stages:
      # list of stages for which the plugin should be enabled
      - local
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566 # optional - LocalStack edge port to connect to
    # lambda:
    #   # Enable this flag to improve performance
    #   mountCode: True
    networks:
      - localstack
functions:
  pastesCrawler:
    handler: src/crawlers/pastes/index.run
    timeout: 60 #sec
    memorySize: 512
    environment:
      AWS_REGION: ${env:AWS_REGION}
      PASTES_URL: ${env:PASTES_URL}
      QUEUE_URL: ${env:QUEUE_URL}
      APP_NAME: ${env:PASTES_APP_NAME}
      PASTES_BUCKET_NAME: ${env:PASTES_BUCKET_NAME}
      AWS_ENDPOINT: ${env:AWS_ENDPOINT}
    name: pastes-crawler-${sls:stage}
    events:
      # Invoke Lambda function every 2nd minute
      - schedule: cron(0/1 * ? * * *)
    tags:
      Team: Crawler
  messageHandler:
    handler: src/handlers/index.consume
    timeout: 30 #sec
    memorySize: 512
    name: message-handler-${sls:stage}
    environment:
      AWS_REGION: ${env:AWS_REGION}
      AWS_ENDPOINT: ${env:AWS_ENDPOINT}
    events:
      - sqs:
          arn: !GetAtt CollectorQueue.Arn
    tags:
      Team: Crawler
resources:
  Resources:
    ContentStorage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:PASTES_BUCKET_NAME}
    CollectorQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: collect-queue.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        Tags:
          - Key: Team
            Value: Crawler
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt CollectorQueueDLQ.Arn
          maxReceiveCount: 3
    CollectorQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: collect-queue-dlq
        MessageRetentionPeriod: 1209600,
        Tags:
          - Key: Team
            Value: Crawler
    PastesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:PASTES_APP_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Tags:
          - Key: Team
            Value: Crawler
        BillingMode: PAY_PER_REQUEST
